server:
  port: 5000
cloud:
  aws:
    region:
      static: us-east-1
      use-default-aws-region-chain: true
      auto: false
    stack:
      auto: false
    credentials:
      access-key: ${{ secrets.AWS_ACCESS_KEY }}
      secret-key: ${{ secrets.AWS_SECRET_KEY }}
